"""Added user generation table

Revision ID: 04e7325831bd
Revises: 
Create Date: 2022-07-02 20:59:16.475610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e7325831bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('mobile_number', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('user_generations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('generation', sa.String(), nullable=True),
    sa.Column('application', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_user_generations_id'), 'user_generations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_generations_id'), table_name='user_generations')
    op.drop_table('user_generations')
    op.drop_table('user')
    # ### end Alembic commands ###
